name: em
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - matplotlib
  - numpy=1.26
  - git
  - simpeg
  - dill
  - jupyterlab
  - ipywidgets
  - mkl-devel
  - pkg-config
  - cmake
  - cython 
  - ninja